### PR TITLE
Fix/mobile menu

### PR DESCRIPTION
**Pull request by Bluesmile82**
This PR fixes and applies the UI kit design to the mobile nav.

- The share button is removed as the designs don't have it anymore.
- The share modal was extracted for consistency

mobileNav

### CODE REVIEW

**Comment by Bluesmile82** [comment]
Ready again!

**Comment by kfilip94** [comment]
checking :eye: :eye:

**Comment by kfilip94** [comment]
- `lts-explore` page doesn't work:

image


- Changing selected tab under the `NDC comparison` page removes the highlight from the menu:

wvmf2-0xbpp

- `About climate watch` page is always highlighted when selecting other pages from the `About` section:

69qp7-oab84

**Comment by Bluesmile82** [comment]
Ready again!

**Pull request merged**
