### PR TITLE
Fix/share links with section

### PR DESCRIPTION
**Pull request by weberjavi**
This PR adds the section hash to the URL to be consumed by the share button on Agriculture profile page.
[Pivotal task](https://www.pivotaltracker.com/story/show/163790009)

### CODE REVIEW

**Comment by simaob** [comment]
One thing that maybe can be fixed on this PR, the map for "Countries actions on their NDCs" has the share button of the original NDC component, and is copying the embed for that. Let's remove that embed link fro the Agriculture page, please!

**Comment by kfilip94** [comment]
@simaob btw. should we add buttons group to `Countries’ Actions in their NDCs/Table` section?
we don't have a design for that but probably buttons should be there, right?

**Comment by simaob** [comment]
Hmmm we probably should, but we don't have it here: https://climate-watch.vizzuality.com/ndcs-content/table either... so maybe let's leave it as is for now. It wasn't on the designs before, and they approved it.

**Comment by kfilip94** [comment]
thanks :+1:  btw2. I see we have this same case with embed links in Drivers of emissions/Future pathways section

**Comment by simaob** [comment]
Let's get rid of it there as well! =)

**Comment by weberjavi** [comment]
No more embed links ☝️

**Pull request merged**
