### PR TITLE
Feature/faq section

### PR DESCRIPTION
**Pull request by weberjavi**
This PR adds a `FAQ` section to About page.

TODO:
Add table on `What document types are included in the timelines on the country profile pages?`

### CODE REVIEW

**Comment by simaob** [comment]
Javi, if there's a simpler format to use instead of the table for the missing bit, feel free to use something else =)

**Comment by simaob** [comment]
if the complexity was something that was causing you trouble, I mean. =)

**Comment by weberjavi** [comment]
Ready to review ☝️ 
[Pivotal task](https://www.pivotaltracker.com/story/show/163084669)
I've added as first iteration the CW repo `Table` component as I was getting some error from the components repo. Would be nice to substitute this component for the one on the components repo (as is more flexible).

Some styles have been changed from the design proposal:
-  Link styles follow the old convention (yellow underline).
-  Font sizes have been increased to follow the same pattern of the other sections of about page.

**Comment by weberjavi** [comment]
Ready again ☝️

**Pull request merged**
