### PR TITLE
Feature/explore by country on country click

### PR DESCRIPTION
**Pull request by weberjavi**
This PR allows user to navigate to selected country page once a country on Agriculture > Countries Context (Explore by Indicator) map is clicked.

[Basecamp](https://basecamp.com/1756858/projects/13795275/todos/381191753)
[Pivotal](https://www.pivotaltracker.com/story/show/164426263)

test here: http://localhost:3000/sectors/agriculture#understand-countries-contexts

### CODE REVIEW

**Comment by simaob** [comment]
Maybe you'll need to use this util: https://github.com/Vizzuality/climate-watch/blob/develop/app/javascript/app/components/countries-select/countries-select.js#L5 `isCountryIncluded`

**Comment by simaob** [comment]
See how it's used here: https://github.com/Vizzuality/climate-watch/blob/develop/app/javascript/app/components/countries-select/countries-select.js#L46

**Comment by weberjavi** [comment]
Ready again ☝️ 
Thanks for the catch @kfilip94 , and @simaob for the hint

**Comment by kfilip94** [comment]
@weberjavi thanks, LGTM :+1:

**Pull request merged**
