### PR TITLE
Fix/description links

### PR DESCRIPTION
**Pull request by Bluesmile82**
Added description links linking to the same page with some params. I styled them with some hover

image

### CODE REVIEW

**Comment by simaob** [comment]
Coolio! =)

**Comment by kfilip94** [comment]
Hey, can we do something about the default tooltips here? Right now, after hover, they show only the first word of the link text:
image

**Comment by Bluesmile82** [comment]
This is the title attribute. I will check it later

**Comment by Bluesmile82** [comment]
This PR is updated with the correct title links now. I have added a bit more of text to make the sentences readable

**Pull request merged**
