### PR TITLE
Feature/ghg regions flying dropdown

### PR DESCRIPTION
**Pull request by weberjavi**
This PR adds new styles to the GHG emissions `countries/regions` dropdown.
Two tasks have been undertaken under this PR:
https://www.pivotaltracker.com/story/show/171813310
https://www.pivotaltracker.com/story/show/171785774
they where so related that needed to do them at once.

Designs could be found here: https://projects.invisionapp.com/d/main?origin=v7#/console/18371781/381684669/inspect

### CODE REVIEW

**Comment by Bluesmile82** [comment]
I'm afraid this change has to be also under the FEATURE_NEW_GHG feature flag

**Comment by weberjavi** [comment]
@Bluesmile82 I've merged `develop` branch and this removed the legend functionality bug.
Also hided the changes behind the feature flag. And added a new `box-shadow` variable, using an already defined shade of grey; also removed the box shadow of the closed selectors to follow the designs.
Added two `classes` to treat the edge cases of `world` and `G77` where the region countries number forces the x scroll to appear.

**Comment by Bluesmile82** [comment]
Thanks for the changes. It works great now but in small screens and mobile the dropdown is breaking the layout. Maybe we can implement some solution for this? In this case I think scrolling will be fine:

@faustoperez what do you think?

image

**Comment by weberjavi** [comment]
@Bluesmile82 ready again :point_up: 
sorry for the back and forth :(

**Comment by Bluesmile82** [comment]
Sorry to bother you again, but in really small screens, like iphone 6/7/8 the countries inside the regions are overlapping each other. Could you check this:
image

**Pull request merged**
