### PR TITLE
Make partners page responsive

### PR DESCRIPTION
**Pull request by Bluesmile82**
About page is mostly responsive, we only needed to change the partners' page disposition:

image

### CODE REVIEW

**Comment by weberjavi** [comment]
In the ``permissions & licensing``  section the link in the bottom of the page overflows the viewport width allowing the user to scroll horizontally    

screen shot 2018-02-02 at 10 37 20

**Comment by simaob** [comment]
@weberjavi I'm not sure we have the texts where they are missing. I mean we did have something for Vizz but not for the others I don't think.

**Comment by simaob** [comment]
It is sad :(

**Comment by Bluesmile82** [comment]
Quick fix! I'm thinking that sometimes the anchor-nav doesn't make very clear that we have more than two elements to chose from. Maybe we could increase the gradient effect so its obvious

**Comment by j8seangel** [comment]
We've included the sticky anchor nav on the about page and added some other fixes on a general review (not related with this PR itself)

**Pull request merged**
