### PR TITLE
Feature/agriculture page

### PR DESCRIPTION
**Pull request by kfilip94**
This PR adds agriculture sector page with basic local routing
Links: [invision design](https://projects.invisionapp.com/d/main#/console/16383011/339735320/preview) and  [basecamp](https://basecamp.com/1756858/projects/13795275/messages/76819853)
screenshot from 2019-01-09 11-44-13

### CODE REVIEW

**Comment by simaob** [comment]
Hey Kamil, can you use a feature flag for now, to show the placeholder that we currently have, unless we have the feature flag to true? So that we can safely merge to develop, and not have to manage extra branches. Tks!

**Comment by kfilip94** [comment]
Sure, I'll restore old placeholder and routing code

**Comment by kfilip94** [comment]
Ready again, to see changes add a `FEATURE_AGRICULTURE=true`

**Comment by kfilip94** [comment]
@weberjavi thank you for pointing this out, I missed it :+1: :)
So, for now, it looks like we are going to leave it without opacity effect, to be consistent with other pages on the Flagship platform, more about it [here](https://vizzuality.slack.com/archives/C6DFY8GVC/p1547042956015800) in the comments section on slack

**Comment by weberjavi** [comment]
then go with it 🚗

**Pull request merged**
