### PR TITLE
Feature/home page video and stories

### PR DESCRIPTION
**Pull request by weberjavi**
This PR adds video end stories section to Home page.
Video doesn't load until play button is pressed.
Only three stories are displayed (but we are receiving five from the backend, should we update backends logic to just fetch three stories, or is the frontend open changes? cc @simaob )

Run `yarn install` before testing this PR, as some dependencies have been updated.

kapture 2018-12-20 at 10 38 27

### CODE REVIEW

**Comment by kfilip94** [comment]
Something is wrong with `Highlighted Stories` height scaling:
screenshot from 2018-12-20 11-35-36

**Comment by kfilip94** [comment]
- Descriptions in Highlited stories section are bolded, but on the design they have regular font,
- About video player: I asked Fanny and video should be displayed in fullscreen mode after click. Sorry for that, I should mention it earlier :(

**Comment by simaob** [comment]
Let's leave the video player full screen for a different PR, please.

**Comment by weberjavi** [comment]
@kfilip94 updated styles to avoid layout break.
Please check it out

**Comment by kfilip94** [comment]
@weberjavi Thank you, now it works, but I noticed when the window resolution is lower, description text covers the WRI icon:
screenshot from 2018-12-20 14-54-50
Maybe in this case, for lower resolution, it'll be good to move WRI logo to the right:
 `right: 0;`
 `padding-right: 30px;`
Or increase story height or description width if it's needed

**Comment by weberjavi** [comment]
@kfilip94 did a small style change to fix the text overlapping issue ☝️

**Comment by kfilip94** [comment]
@weberjavi Thank you, great job :+1:

**Pull request merged**
