### PR TITLE
Adds slug to api/v1/data endpoints resources

### PR DESCRIPTION
**Pull request by simaob**

### CODE REVIEW

**Comment by kfilip94** [comment]
Hey @simaob, thanks a lot for adding this. There are things I found:
- **data-sources** slugs are always `null`, can you confirm that you see the same problem?
image

- I don't see slugs for Pathways filters

**Comment by simaob** [comment]
OK on data sources I'm seeing it as well, though not sure why. I'll check it after my next meeting.
For Pathways I need to do that on another project and then deploy it. It's a separate application.

**Comment by simaob** [comment]
OK, the source slug should now be fixed! =)

**Comment by simaob** [comment]
Pathways is also fixed.

**Pull request merged**
