### PR TITLE
Info tooltip on multiple location charts selectors (`locations` and `models`)

### PR DESCRIPTION
**Pull request by weberjavi**
This PR fixes Viscreator info tooltip to display only in charts that allow multiple locations selection.

https://basecamp.com/1756858/projects/13795275/todos/354837515 
 

kapture 2018-06-18 at 15 33 58

### CODE REVIEW

**Comment by Bluesmile82** [comment]
The info tooltip is not working for me. Although the icons are working as expected. Maybe this is still TBI

**Comment by weberjavi** [comment]
:( the tooltip should be working

**Comment by simaob** [comment]
yes you're right, they are not showing :$ I missed that, sorry!

**Comment by weberjavi** [comment]
@simaob , @Bluesmile82 it should be fixed now

**Comment by weberjavi** [comment]
@Bluesmile82 is this working for you?

**Pull request merged**
