### PR TITLE
Feature/generic data upload worker

### PR DESCRIPTION
**Pull request by agnessa**
Depends on https://github.com/ClimateWatch-Vizzuality/climate-watch-gems/pull/8 to simplify code (by removal of repetitive code)

Update:
* Updated Gemfile with new version of cw data uploader gem
* Change deployment scripts with referral to new S3_BUCKET_NAME and new secret vars (the same ones as in South Africa platform)
* Add new CW_FILES_PREFIX env variable (needs to be set both in production and staging as they will be different, they represent the path to folders in s3 bucket), i.e. `folder_in_bucket/staging/climate-watch/` -> always with a slash in the end ❗️ 
* Add missing socioeconomics page to admin panel

### CODE REVIEW

**Comment by agnessa** [comment]
thanks! updated the gem

**Comment by simaob** [comment]
Hi guys, I see a conflict here. Can someone have a look, please? Thanks!

**Comment by aabdaab** [comment]
I resolved the conflict and added `CW_FILES_PREFIX` to deployment scripts like in South Africa

**Comment by aabdaab** [comment]
I will copy the files into the new bucket now

**Pull request merged**
