### PR TITLE
Enables comparison betweeen locations-documents

### PR DESCRIPTION
**Pull request by simaob**
This PR implements the changes to enable comparing NDC indicators between countries and different documents, it builds on the existing endpoint to enable a new parameter:

e.g.:
`locations_documents=ALB-first_ndc,DZA-indc`

This will be used instead of the current `location` parameter.

The route is then:

`/api/v1/ndcs?locations_documents=DZA-indc,ALB-first_ndc&category=overview&source[]=CAIT&source[]=WB&source[]=NDC%20Explorer`

It expects a comma separated list of {iso-code3}-{document_slugs} pairs.

This endpoint doesn't yet include all of the data, as some bits are still work in progress, but they won't change the format of neither the request nor the response.

In regards to the laws and policies that is still missing overall, but we'll try to use the same endpoint for those as well. More on that later.

### CODE REVIEW

**Comment by simaob** [comment]
Note that I changed to `locations_documents` instead of `locations_docs` for consistency with the filtering using `document`.

**Comment by kfilip94** [comment]
ok, checking

**Comment by kfilip94** [comment]
Probably I'm doing something wrong, but once I open the request:
`http://localhost:3000/api/v1/ndcs?locations_documents=DZA-indc,ALB-first_ndc&category=overview&source[]=CAIT&source[]=WB&source[]=NDC%20Explorer`
I get all documents data for all countries, so I suspect something goes wrong there? Or do I need to update something else?

**Comment by simaob** [comment]
My bad! forgot to push the final change!

**Pull request merged**
