### PR TITLE
Add Pathways section, filters and download link

### PR DESCRIPTION
**Pull request by Bluesmile82**
WIP - Until the links PR is merged and I can finish the link to pathways part. Also methodology is missing

This PR adds the pathways section to the data explorer:
- [x]  Add section on the router
- [x]  Fetch data, metadata from the production URL
- [x]  Add filters
- [x]  Fix download link
- [x] Add methodology from the different model, scenario, and indicator
- [x]  Fix double fetching
- [x]  Fix link to the module with params

image

### CODE REVIEW

**Comment by simaob** [comment]
The links PR is now merged.

**Comment by simaob** [comment]
@Bluesmile82 is this ready for review? can we remove the WIP?

**Comment by Bluesmile82** [comment]
Ready!

**Comment by Bluesmile82** [comment]
Should work now! Region locations are showing an id on the fetch because they don't have a iso_code

**Comment by simaob** [comment]
So the backend needs to adapt to this? @agnessa can the backend handle the id if that is passed? or should we create "fake" iso's?

**Comment by simaob** [comment]
The link back from the Data Explorer to Pathways doesn't seem to be working when selecting a location that has an ISO code. As it doesn't get translated to an id.

**Comment by Bluesmile82** [comment]
Ready again! Thanks for the catch. Too many edge cases 😅

**Comment by weberjavi** [comment]
@Bluesmile82 just a doubt, would make sense to store the bulk data (without filters) and use it when filters are cleared instead of fetching again all the data every time the user clears a selection?

**Comment by Bluesmile82** [comment]
I agree that this is maybe depending too much on the backend but after implementing pagination the load time will be much faster

**Comment by simaob** [comment]
There's another PR with pre-filtering across selectors, so maybe that can be done afterwards!

**Pull request merged**
