### PR TITLE
Feature/explore emissions button

### PR DESCRIPTION
**Pull request by weberjavi**
This Pr adds functionality to `Explore Emissions` and `Explore Pathways` button on Agricuture's `Drivers of emissions` section.
[Pivotal task](https://www.pivotaltracker.com/story/show/163790016)
[Designs](https://projects.invisionapp.com/d/main#/console/16383011/339735319/preview)

### CODE REVIEW

**Comment by kfilip94** [comment]
Good job :+1:
I found one thing: when we click on `Future Pathways` and then, before the data will be loaded, click on `Explore pathways`, pathways page will open but query params will be null/undefined:
`http://localhost:3000/pathways/model?currentLocation=undefined&category=null&indicator=null&model=null`
ezgif-1-8202aec42a58
Should we set default search?

**Comment by weberjavi** [comment]
Ready to review ☝️ 
Thanks @kfilip94 for spotting the bug 🔎 🐛 
Added the default link.

**Comment by kfilip94** [comment]
Thanks for fixing this :+1: But there is one more thing :cry:
For countries where we don't have any data about pathways, after click on explore emissions, the default link is set as `/pathways/model` but I think it would be good to pass country even if rest of the params is empty.
e.g. we don't have here category and indicator data for Lithuania, but we have location and model:
`location: {label: "Lithuania", value: 146} , 
category: null, 
indicator: null, 
model: {label: "Global Change Assessment Model"}`

**Comment by weberjavi** [comment]
@kfilip94 ready again ☝️

**Pull request merged**
