### PR TITLE
Feature/hide quantifications contained countries

### PR DESCRIPTION
**Pull request by weberjavi**
This PR removes quantifications data from `GHG emissions` chart on `contained` version of CW.  
[Pivotal task](https://www.pivotaltracker.com/story/show/156649841) . 

kapture 2018-04-12 at 18 54 43

Check it on [`http://localhost:3000/contained/countries/USA`](http://localhost:3000/contained/countries/USA)

### CODE REVIEW

**Comment by weberjavi** [comment]
Thanks!!
Much more clean.
👍

**Comment by weberjavi** [comment]
@simaob changes made to address the requests (that already where on the pivotal story :(

**Comment by simaob** [comment]
I find solace in the fact that I didn't forget to specify it =p
And a lesson learned on this beautiful sunny Friday: "in Pivotal Tracker descriptions matter". ;)

**Comment by simaob** [comment]
One thing left to remove on this line: https://github.com/Vizzuality/climate-watch/blob/feature/hide-quantifications-contained-countries/app/javascript/app/components/country/country-ghg-emissions/country-ghg-emissions.js#L107

If we are in the contained we shouldn't show these slugs: 'ndc_quantification_UNDP', 'ndc_quantification_WRI' (in the metadata modal I mean), we'd only show the `source`.

**Comment by weberjavi** [comment]
🎯

**Pull request merged**
