### PR TITLE
Feature/flag mycw

### PR DESCRIPTION
**Pull request by weberjavi**
This PR prepares my-cw branch to be merged with `develop` branch.
It adds a flag on the `.env` file to activate or deactivate My CW feature.  
`FEATURE_MY_CLIMATEWATCH=true`   
 
It is used both in the `app-routes.js` file and in the `tools-nav` component

### CODE REVIEW

**Comment by simaob** [comment]
Make sure to add it to the `k8/` staging and production files as well.

**Comment by weberjavi** [comment]
@simaob is that needed? being only a front end flag sounds kinda weird to be in those config files.  
In case `FEATURE_MY_CLIMATEWATCH` is added should I also add `FEATURE_QUANTIFICATIONS` flag?

**Comment by simaob** [comment]
Oh you're right. But you need it on both the Dockerfile and Jenkinsfile!

**Comment by weberjavi** [comment]
Ready to review

**Pull request merged**
