### PR TITLE
Feature/contained links

### PR DESCRIPTION
**Pull request by Bluesmile82**
This PR changes every ```/contained``` link from the NDCs partnership to open them in new tabs. This includes:

- NDC Linkages - Links in map
- NDC Content - Links in map
- NDC Content - Links in table
- NDC Content - Search dropdown link

Extra:

Fixes dropdown search button

image

### CODE REVIEW

**Comment by simaob** [comment]
Hey Álvaro, is this not up to date with the footer changes?
I noticed that the "Download links" on the toolbars isn't opening on a new page, that would another one to open like that! Thanks!

**Comment by Bluesmile82** [comment]
You are right! Just rebased and added the download link target

**Comment by simaob** [comment]
> You are right! Just rebased and added the download link target

and also to update to link to the full route, instead of the contained!

**Comment by Bluesmile82** [comment]
Ready again!

**Pull request merged**
