### PR TITLE
Feature/country lts section

### PR DESCRIPTION
**Pull request by Bluesmile82**
This is the new LTS section for the country page.
It has:

- Title, similar to the NDCs section
- Content of the LTS summary of the LTS page
- Info button opening metadata for LTS
- Compare button linking to the new compare-all page with the LTS document selected
- Share button with a new LTS summary embed
- Primary explore button leading to the LTS page

This section doesn't show if the LTS doesn't have content

image

### CODE REVIEW

**Comment by kfilip94** [comment]
checking

**Comment by Bluesmile82** [comment]
@fannycc The style is here. Maybe we merge that gray with the darker one. Is that what you don't like? 🦆  image

**Comment by fannycc** [comment]
Screenshot 2020-05-20 at 13 26 05
yeah, those are correct. The compare has a different style tho :) not the secondary style.

**Comment by kfilip94** [comment]
- In the embed view of this component we don't see any information about the country that we selected, how we should deal with that @fannycc?
image
the same for the ndc section:
image
- How about the case when a country doesn't have LTS submitted, but the `LTS Content Overview` section is still visible:
x81cg-utywo

**Comment by Bluesmile82** [comment]
Yes, maybe we should remove also that item from the navbar if the LTS doesn't have data. But we can't know it until we do the fetch. Should we show always an LTS section without content? Or do you prefer to remove it completely?

**Comment by fannycc** [comment]
hey, so reading you and without further details I guess that it doesn't make much sense to select the embed section for something that can't be embed?. Or the problem is that when I embed the LTS of let's say Algeria in the embed it doesn't say the `country name` ? 
And about the overview shown in a selected country, i guess we could put a placeholder like: This country hasn't submitted any Long Term Strategies, that's also useful information. Please feel free to ping me during the day in slack about this if necessary

**Comment by kfilip94** [comment]
> Or the problem is that when I embed the LTS of let's say Algeria in the embed it doesn't say the country name

☝️ this one ^^

About the `LTS section` it makes sense to show the message about lack of LTS document, totally agree 👍

**Comment by Bluesmile82** [comment]
I added the new text to the No content countries, on the country and Lts page. 
Now the section always shows
Also, I changed the secondary button border color.

image
image

**Pull request merged**
