### PR TITLE
Fix 2020 tracker

### PR DESCRIPTION
**Pull request by tsubik**
Label slug was not returned for indicator values.

### CODE REVIEW

**Comment by tsubik** [comment]
I totally do not understand why sometimes label slug is not returned, and when it should be returned as clearly on that page was needed.

**Comment by Bluesmile82** [comment]
Before, the label was returned only when we had a correspondent indicator with a value. I thought we hadn't changed that but maybe we did

**Comment by tsubik** [comment]
Take a look now @Bluesmile82 , both LTS Explorer and 2020 NDC tracker should work fine now.

**Comment by Bluesmile82** [comment]
Thanks! The modules are working fine now again!

**Pull request merged**
