### PR TITLE
Feature/ndcs enhancements

### PR DESCRIPTION
**Pull request by kevinlustig**
Additional updates per WRI input: 
1. Removed "Ambiguous Intent" legend category
2. Added a third "factoid" to the 2020 Ambition Tracker page
3. Changed LTS Tracker url to /lts-tracker

### CODE REVIEW

**Comment by kevinlustig** [comment]
Can we get this one deployed to staging?

**Comment by simaob** [comment]
Shoot, thought I did that before I left. Just pressed the buttons to deploy. Should be up in 15min

**Comment by kevinlustig** [comment]
TY!

**Comment by kevinlustig** [comment]
WRI has approved these changes for deployment to production.

**Comment by simaob** [comment]
Alright. I'll get them up tomorrow morning!

**Pull request merged**
