### PR TITLE
Feature/data explorer ndc indc linkable

### PR DESCRIPTION
**Pull request by Bluesmile82**
This PR links the INDC text from the Data Explorer/ NDC-SDG Linkages table to the correspondent text in the document.

image

### CODE REVIEW

**Comment by simaob** [comment]
The document type and document language are now passed via the API. Is this what you needed?

**Comment by weberjavi** [comment]
@Bluesmile82 is this ☝️ ready to review? it has some conflicts

**Comment by Bluesmile82** [comment]
Conflicts solved!

**Comment by weberjavi** [comment]
There are some cases in which highlighted text (on NDCs country full page) is not inside the view when joining the page, there are also some cases where there is other text highlighted.  

Test on: http://localhost:3000/data-explorer/ndc-sdg-linkages?ndc-sdg-linkages-goals=3&page=1
Testing on **Burkina Faso** INDC texts. 

kapture 2018-08-07 at 18 13 38

**Comment by Bluesmile82** [comment]
@weberjavi Good catch! It seems that for some of the targets the backend return several linkages.  We need a idx attribute for the ScrollToHighlightIndex component. I'm not sure if we can find this in the backend @simaob @agnessa? Maybe @j8seangel can throw some light too

**Comment by simaob** [comment]
I feel that this is the current behaviour that we have on the NDC-Full Text page anyway, so maybe doesn't need to be sorted in this branch just yet.

**Comment by simaob** [comment]
So if we are not handling the issue of the multiple linkages only here, is the rest good to go?

**Comment by Bluesmile82** [comment]
We can handle it in some other task. But I think we are missing some information from the backend. @weberjavi Do you approve without this change?

**Pull request merged**
