### PR TITLE
Update home images

### PR DESCRIPTION
**Pull request by weberjavi**
This PR updates home page images to fit the last changes in the interface and new sections.

### CODE REVIEW

**Comment by simaob** [comment]
Shoot... can you update the pathways screenshot? 🤦‍♂️  see staging for the latest version includes the text "Data provided by" that Jorge added yesterday. Would this be quick to update?

Thanks!

**Comment by weberjavi** [comment]
@simaob, @Bluesmile82 there is another image left, I'll make you know when this PR is ready to review 😅

**Comment by weberjavi** [comment]
@simaob, @Bluesmile82 ready

**Comment by simaob** [comment]
Looks good to me =)

**Pull request merged**
