### PR TITLE
Add icon to data explorer link

### PR DESCRIPTION
**Pull request by weberjavi**
This PR adds a `download` icon to Data Download link on `tools-nav`
[Pivotal task](https://www.pivotaltracker.com/story/show/160993916)

image

### CODE REVIEW

**Comment by kfilip94** [comment]
Looks great :+1:  should the icon be visible in the responsive menu too?

**Comment by weberjavi** [comment]
Not sure, it probably makes sense. @faustoperez ? ☝️ 
Also I've noticed that we have `My Climate Watch` link twice
image

**Comment by faustoperez** [comment]
Please remove the _MY CW_ and _DATA EXPLORER_ items from the blue list and put them at the bottom besides the share icon. Thanks! 💐

**Comment by faustoperez** [comment]
And yes, @kfilip94 please add the icon in the responsive version too :)

**Comment by weberjavi** [comment]
Taking care of this

**Comment by weberjavi** [comment]
☝️ ready to review again

**Comment by kfilip94** [comment]
Looks great on mobiles now :+1: 
But I noticed that for mobile view, after clicking  on `MY CW` or `DATA EXPLORER`, the menu is still visible instead disappear, what can be confusing, because we don't see if one of these pages is loaded or not :confused:  Could you fix it in this PR?

**Comment by weberjavi** [comment]
@kfilip94 added closing menu functionality ☝️

**Pull request merged**
