### PR TITLE
Fix/agriculture feedback fixes

### PR DESCRIPTION
**Pull request by weberjavi**
This Pr fixes two small issues on Agriculture profile:
- Add ellipsis to bar charts on Countries Context > Explore by Indicator 
(approved by @faustoperez ©️)

[Basecamp](https://basecamp.com/1756858/projects/13795275/todos/381191866)

image

- Remove sentences when no data on water card
[Basecamp](https://basecamp.com/1756858/projects/13795275/todos/381192389)

image

### CODE REVIEW

**Comment by kfilip94** [comment]
@weberjavi I think it would be good to center vertically and horizontally this `No water withdrawal...` message.
I'm almost sure that we will receive a feedback about showing whole country name or at least tooltip with full country name, should we think about it now @simaob or leave it as it is?

**Comment by simaob** [comment]
What do you mean? The country name is in that message already, no?

**Comment by kfilip94** [comment]
Sorry, I was talking about the first task with text overflow:
54025074-b5f45080-4199-11e9-9644-b5227c4d7795

**Comment by simaob** [comment]
oh right. yes we should have a tooltip probably, to show the full name.

**Comment by weberjavi** [comment]
@kfilip94 centered `No data` sentence.
About full name: 
The way is built now the top ten list is with `pseudoelements` absolutely positioned (for country label and indicator value), Positioning the labels as relative will have some implications on list height and bars vertical alignment (as the height of some elements will be bigger than others)

**Comment by weberjavi** [comment]
ok @simaob will go with the tooltip solution then

**Comment by simaob** [comment]
Thanks!

**Comment by weberjavi** [comment]
@simaob, @kfilip94 added tooltip ☝️

**Comment by weberjavi** [comment]
mmm conflicts

**Comment by weberjavi** [comment]
Fixed

**Comment by kfilip94** [comment]
@weberjavi thank you :)
I noticed that for a mobile view this text overflow is unnecessary:
screenshot from 2019-03-08 14 19 38
Sorry I didn't discover it earlier :(

**Comment by simaob** [comment]
Kamil is that a quick thing that maybe you could do, given that Javi is away for the weekend already?

**Comment by kfilip94** [comment]
Ok sure, I'll try to do it today :)

**Comment by kfilip94** [comment]
@simaob done

**Pull request merged**
