### PR TITLE
Feature/responsive homepage

### PR DESCRIPTION
**Pull request by kfilip94**
This PR makes homepage more responsive for smaller resolutions, especially for mobiles:
1fr6e-usiyh

### CODE REVIEW

**Comment by weberjavi** [comment]
Hey @kfilip94, overall is looking great 📱 👍 
Just some small tweaks that could be made:
Latest updates section is outside the `layout` of the page (should be aligned with navbar CW logo). Its paddings are being manually set and maybe is better to put it inside a a column.

image

The same for the `How can climate watch help you` section, when not displaying the pictures the remaining slide is misplaced 

image

**Comment by kfilip94** [comment]
@weberjavi thank you, ready again :arrow_up:

**Comment by simaob** [comment]
@weberjavi for your attention when you are available.

**Comment by weberjavi** [comment]
on it ☝️

**Pull request merged**
