### PR TITLE
fix typo in FAQ per request

### PR DESCRIPTION
**Pull request by sw1115**

### CODE REVIEW

**Comment by sw1115** [comment]
Hi Álvaro, as we just made some final changes on FAQ, could I trouble you to deploy it to production if all looks good to you? Since we had an external request to fix one typo in the text. Thank you!

**Review by Bluesmile82 — APPROVED** [review]
Thanks!

**Comment by sw1115** [comment]
Hi @Bluesmile82, i am following up here since the changes of module names are still not on production. Could you please check it again when you get the time? Thank you so much! :)

**Comment by Bluesmile82** [comment]
Hi! I'm deploying to production. Maybe in the future will be nice to specify on the PR the desired date for publishing to production

**Pull request merged**
