### PR TITLE
Include country name tooltip by default in map

### PR DESCRIPTION
**Pull request by j8seangel**
Show country name tooltip by default in maps that could be overwritten passing an external tooltipId.

### CODE REVIEW

**Comment by simaob** [comment]
I've marked this PR as "don't-merge-yet", as the names that we have in the geometries are not the best fit... For instance "Kingdom of Spain" and "Republic of Portugal".

**Comment by j8seangel** [comment]
Yes, I know we are cleaning the topojson file that fix will be included inside this task https://www.pivotaltracker.com/story/show/152374938

**Comment by j8seangel** [comment]
Names updated in the PR https://github.com/Vizzuality/climate-watch/pull/189

**Comment by simaob** [comment]
Thanks! =) good names now!

**Pull request merged**
